= Certification Test Plan
:sectnums:
David Harris
3 July 2025

This is a draft Certification Test Plan.  It reflects the coverpoints and tests
presently being developed in the https://github.com/openhwgroup/cvw-arch-verif/:[cvw-arch-verif] repository soon to migrate to
https://github.com/riscv-non-isa/riscv-arch-test:[riscv-arch-test] cvw branch.  It is intended for discussion as a possible format
of test plan for RISC-V Certification.

== Introduction

This Certification Test Plan describes the coverpoints and tests to certify RISC-V profiles.  It summarizes the profiles intended to be supported and the test suites that need to run on each profile.  It also summarizes the contents of each test suite.

=== Coverpoints and Tests

Coverpoints are the key to certification.  They are the features of the RISC-V architecture that need to be tested in order to certify a profile.  Each coverpoint has a set of tests that exercise it, and each test has a set of coverpoints that it hits.

This test plan defines the coverpoints that must be hit for each profile, and outlines the tests that hit those coverpoints.  The tests are self-checking, and report pass/fail results.  The coverage report confirms that the tests hit all the coverpoints.

Coverpoints are written in SystemVerilog, and are designed to be used with the Extended https://github.com/riscv-verification/RVVI:[RISC-V Verification Interface] (RVVI).  They are written to be independent of the DUT (Device Under Test), so that they can be used with any RISC-V implementation. footnote:[Extended RVVI adds signals for virtual memory verification, including physical and virtual instruction and data addresses, and I/D TLB entries.] Functional coverage is collected using SystemVerilog infrastructure adapted from https://github.com/riscv-verification/riscvISACOV[riscvISACOV] footnote:[Portions of riscvISACOV that depend on proprietary Synopsys code such as a disassembler have been replaced with open-source equivalents].

Coverpoints are organized into .svh SystemVerilog coverage files, each of which contain one or more covergroups, each of which contain one or more coverpoints.  Coverage files apply to a DUT with a particular set of extensions.  For example, the I_coverage.svh coverage file is used for any 32 or 64-bit DUT that supports the I extension. The ZicsrM_coverage.svh coverage file applies to a DUT that supports the Zicsr extension and machine mode.  The ZicsrS_coverage.svh coverage file applies to a DUT that supports the Zicsr extension and supervisor mode.

Tests are written in assembly language .S files.Tests are organized into directories for each extension, and into a privileged directory.  The coverpoints are hit by running all of the applicable tests in a directory.  For example, RV32I coverage involves running add.S, addi.S, sub.S, etc.  RV64I coverage also involves running addw.S, which is unique to RV64.

=== Current Status

At present, coverpoints and tests are being developed in the https://github.com/openhwgroup/cvw-arch-verif/:[cvw-arch-verif] repository and being tested on the https://github.com/openhwgroup/cvw:[CORE-V Wally] processor.  The goal is to be able to certify RVA23S64 as well as spec-compliant machine mode.

This test plan exists in the form of spreadsheets, and is being converted to ASCII Doc.

As of June 2025, all unprivileged and privileged RVA23S64 features have tests hitting 100% of the coverpoints, with the following exceptions:

* The Vector extension is in progress
* Interrupt tests coverpoints complete, tests partially complete
* PMP tests in progress
* Virtual memory: Sv39 and Sv48 100% coverage, Sv48 debugging one coverpoint
* Hypervisor not started

== Certification Process

Certifying a RISC-V Device-Under-Test (DUT) involves the following steps:

* Selecting a profile for the DUT
* Providing a Unified Database (UDB) with configuration options for the DUT, such as optional extensions, peripheral addresses, and PMP granularity
* Generating self-checking tests based on the selected profile and UDB
* Running the tests and reportig pass/fail
* Generating a coverage report confirming that the tests hit all the coverpoints footnote:[Open question whether to generate coverage from a Sail log or the DUT.  DUT requires a suitable testbench with RVVI interface, but is more robust to check that the tests fully run.]

== Profiles & Test Suites

This test plan addresses Phase 0, Phase 1, and Phase 2 RISC-V certification objectives, including the following ratified and unratified profiles:

* https://drive.google.com/file/d/1Kg7Ner5ZlxFDclf92-9Tz88JvmZWt5Wb/view[RVI20 Profile] (Ratified)
** RV{32/64}IMAFDC_Zifencei_Zicntr_Zihpm with machine mode
* Microcontroller Profile (Not Ratified, but market demand)
** RV{32/64}IMC_Zifencei_Zicsr_Zicntr with machine mode, user mode, interrupts, PMP16 footnote:[Tentative; may need updating based on the MRD Market Requirements Document]
* https://github.com/riscv/riscv-profiles/blob/main/src/rvb23-profile.adoc#rvb23s64-profile[RVB23S64 Profile] (Ratified)
** RVA23 less vector and hypervisor
* https://github.com/riscv/riscv-profiles/blob/main/src/rva23-profile.adoc#rva23s64-profile[RVA23S64 Profile] (Ratified)

Table XREF summarizes the coverage files applicable to each profile.


== General Test Plan Strategy

Coverpoints are written with one file that covers both RV32 and RV64, to reduce the duplication and risk of becoming out of sync.  When a coverage file contains coverpoints that apply only to one XLEN or the other (e.g. 32 or 64-bit corner values), they are separated by ``ifdef XLEN32` or `XLEN64` directives.

Privileged tests are mostly written by hand and share a single .S file that can be compiled for either RV32 or RV64, again with `ifdef` directives to separate the two.  Unprivileged tests are generated from a template using a Python script, and are divided into RV32 and RV64 directories because the random values differ with XLEN.

== Unprivileged Test Plan

Unprivileged tests exercise every instruction using every applicable source and destination register, and reasonable corners of source values.  They are intended for certification, not verification. For example, they do not test all difficult floating-point cases.

The unprivileged test plan is written to be easily reviewed by a human, and to be automatically converted to machine-readable coverpoints and tests.
It is defined with spreadsheets in comma-separated value (CSV) format.

=== Unprivileged Tests

Unprivileged tests sweep some feature under test (such as the destination register rd) while randomizing all applicable register IDs and source values.  For example, the unprivileged test for the cp_rd coverpoint of the add instruction contains 32 add instructions, using the 32 different choices of rd.  The rs1 and rs2 register numbers and values are selected randomly. footnote:[The random values should be selected in a deterministic way so that regenerating tests use the same random values where possible, minimizing differences between tests.  This can be done by seeding the random number generator with a has of the instruction and coverpoint name.]

Unprivileged tests are designed to never trap. Their results are independent of the privilege mode in which they are run, so they generally are run only in machine mode.  They generally involve no privileged instructions, except that floating-point and vector tests turn on the mstatus.{FS/VS} bits to enable these extensions.

=== Unprivileged Coverpoints

The following coverpoints are used in most of the unprivileged test plans in subsequent sections.

[cols="1,3" options=header]
|===
|Coverpoint|Definition
|cp_asm_count| Number of times the instruction is executed in the test, must be greater than 0.
|cp_rs1| The rs1 register number (0-31) used in the instruction.
|cp_rs2| The rs2 register number (0-31) used in the instruction.
|cp_rd| The rd register number (0-31) used in the instruction.
|===

*** x, words in coverpoints

=== I Extension

[options=header]
|===
|Instruction|Type|RV32|RV64|cp_asm_count|cp_rs1|cp_rs2|cp_rd|cp_rs1_corners|cp_rs2_corners|cr_rs1_imm_corners|cr_rs1_rs2_corners|cmp_rd_rs1_eqval|cmp_rd_rs2_eqval|cmp_rs1_rs2|cmp_rd_rs1|cmp_rd_rs2|cmp_rd_rs1_rs2|cp_offset|cp_uimm|cp_imm_corners|cp_rs1p|cp_rs2p|cp_rdp|cp_fdp|cp_fs2p|cp_imm_mul|cp_bs|cp_rnum|cp_sc|cbo|cp_fpr_hazard|cp_gpr_hazard|cp_fs1|cp_fs2|cp_fs3|cp_fd|cp_fs1_corners|cp_fs2_corners|cp_fs3_corners|cmp_fd_fs1|cmp_fd_fs2|cmp_fd_fs3|cp_frm|cp_csr_fflags|cp_csr_frm|cr_fs1_fs2_corners|cr_fs1_fs3_corners|cr_fs1_fs2_corners|cr_fs1_fs3_corners|cp_fclass|cp_NaNBox|cp_fs1_badNB|cp_fs2_badNB|cp_fs3_badNB|cp_align
|add|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|addi|I|x|x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|addiw|I||x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|addw|R||x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|and|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|andi|I|x|x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|auipc|U|x|x|x|||x|||||||||||||20bit||||||||||||w|||||||||||||||||||||||
|beq|B|x|x|x|x|x||x|x||x|x||x||||x||||||||||||||r|||||||||||||||||||||||
|bge|B|x|x|x|x|x||x|x||x|x||x||||x||||||||||||||r|||||||||||||||||||||||
|bgeu|B|x|x|x|x|x||x|x||x|x||x||||x||||||||||||||r|||||||||||||||||||||||
|blt|B|x|x|x|x|x||x|x||x|x||x||||x||||||||||||||r|||||||||||||||||||||||
|bltu|B|x|x|x|x|x||x|x||x|x||x||||x||||||||||||||r|||||||||||||||||||||||
|bne|B|x|x|x|x|x||x|x||x|x||x||||x||||||||||||||r|||||||||||||||||||||||
|jal|J|x|x|x|||x|||||||||||||jal||||||||||||w|||||||||||||||||||||||
|jalr|JR|x|x|x|nx0||x||||||||nx0|||jalr||x||||||||||||rw|||||||||||||||||||||||
|lb|L|x|x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||byte
|lbu|L|x|x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||byte
|ld|L||x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||
|lh|L|x|x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||hword
|lhu|L|x|x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||hword
|lui|U|x|x|x|||x|||||||||||||20bit||||||||||||w|||||||||||||||||||||||
|lw|L|x|x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||word
|lwu|L||x|x|nx0||x||||||||nx0|||||x||||||||||||rw|||||||||||||||||||||||word
|or|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|ori|I|x|x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|sb|S|x|x|x|nx0|x|||x|||||||||||x||||||||||||r|||||||||||||||||||||||byte
|sd|S||x|x|nx0|x|||x|||||||||||x||||||||||||r|||||||||||||||||||||||
|sh|S|x|x|x|nx0|x|||x|||||||||||x||||||||||||r|||||||||||||||||||||||hword
|sll|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|slli|IS|x|x|x|x||x|x||||x|||x||||x|||||||||||||rw|||||||||||||||||||||||
|slliw|IS||x|x|x||x|x||||x|||x||||5|||||||||||||rw|||||||||||||||||||||||
|sllw|R||x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|slt|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|slti|I|x|x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|sltiu|I|x|x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|sltu|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|sra|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|srai|IS|x|x|x|x||x|x||||x|||x||||x|||||||||||||rw|||||||||||||||||||||||
|sraiw|IS||x|x|x||x|x||||x|||x||||5|||||||||||||rw|||||||||||||||||||||||
|sraw|R||x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|srl|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|srli|IS|x|x|x|x||x|x||||x|||x||||x|||||||||||||rw|||||||||||||||||||||||
|srliw|IS||x|x|x||x|x||||x|||x||||5|||||||||||||rw|||||||||||||||||||||||
|srlw|R||x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|sub|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|subw|R||x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|sw|S|x|x|x|nx0|x|||x|||||||||||x||||||||||||r|||||||||||||||||||||||word
|xor|R|x|x|x|x|x|x|x|x||x|x|x|x|x|x|x|||||||||||||||rw|||||||||||||||||||||||
|xori|I|x|x|x|x||x|x||x||x|||x|||||x||||||||||||rw|||||||||||||||||||||||
|fence|F|x|x|x|||||||||||||||||||||||||||||||||||||||||||||||||||
|===

=== M Multiply Extension

=== Zca Compressed Extension

=== Zcb Additional CompressedExtension

=== F Floating-Point Extension

=== D Double-Precision FP Extension

=== Zfh Half-Precision FP Extension

***

=== V Vector Extension

The vector coverpoints are intended to be flexible to support the full V extension, the Zve* embedded vector extensions, and arbitrary mixes of supported vector length (VLEN), element lengths (SEW~MIN~, ELEN), and floating-point precisions.

The vector extension is huge.  The testplan is partitioned into three unprivileged portions discussed here, and three privileged portions (ZicsrV, ExceptionsV, SsstrictV) discussed in XREF.

The full V extension supports all selected element widths SEW={8, 16, 32, 64}.  The vector coverage files and tests are organized by SEW.  Thus, a DUT could handle any contiguous subset of SEW from SEW~MIN~ to ELEN.  For example, a DUT with SEW~MIN~=16 and ELEN=32 would support SEW={16, 32}.

The tests detect VLMAX and set the vector length accordingly, up to some configurable maximum VLEN (default 4096 bits, although the vector extension theoretically supports up to 65536).  Therefore, there is no need for different test suites for different VLENs.

==== Vector File Organization

Figure *** summarizes the structure of the coverpoint and test files for the vector extension.  The unprivileged vector tests are organized by integer (Vx), load/store (Vls), and floating-point (Vf) types of instructions. Each applies to SEW=8, 16, 32, and/or 64. The ExceptionsV, ZicsrV, and SsstrictV privileged tests are described in section XREF.

The vector tests are organized by XLEN=32 and XLEN=64 because the scalar registers behavior differs by XLEN.  For example, vadd.vx with SEW=64 sign-extends XLEN=32 scalar registers but does not modify XLEN=64 scalar registers.  For a given XLEN, the vector tests are organized by type (Vx/Vls/Vf) and SEW (8/16/32/64).  Each directory contains a .S file for every vector instruction of that type footnote:[Certain instructions are omitted if not supported for a given SEW.  For example, widening add vwadd.vv is not supported for SEW=64, and vrgatherei16.v is not supported for SEW=8.].  Vector load/store instructions run with any SEW but also specify EEW as part of the instruction name.  For example, vle8.v and vle16.v can both be executed in either SEW=8 or SEW=16, and the EMUL behavior is different between these modes.  Therefore, all the load/store variants are included in all of Vls{8/16/32/64}.

fcov
    unpriv
        Vx8_coverage.svh
        Vx16_coverage.svh
        Vx32_coverage.svh
        Vx64_coverage.svh
        Vls8_coverage.svh
        Vls16_coverage.svh
        Vls32_coverage.svh
        Vls64_coverage.svh
        Vf16_coverage.svh
        Vf32_coverage.svh
        Vf64_coverage.svh
      priv
        ExceptionsV_coverage.svh
        ZicsrV_coverage.svh
        SsstrictV_coverage.svh
tests
    rv32
        Vx8
            vadd.vv.S
            vadd.vx.S
            vadd.vi.S
            vsub.vv.S
            ...
        Vx16
            vadd.vv.S
            ...
        Vx32
            vadd.vv.S
            ...
        Vx64
            vadd.vv.S
            ...
        Vls8
            vle8.v.S
            vle16.v.S
            vle32.v.S
            vle64.v.S
            vlseg2e8.v.S
            ...
        Vls16
            vle8.v.S
            ...
        Vls32
            vle8.v.S
            ...
        Vls64
            vle8.v.S
            ...
        Vf16
            vfadd.vv.S
            vfadd.vf.S
            vfwadd.vv.S
            vfsub.vv.S
            ...
        Vf32
            vfadd.vv.S
            ...
        Vf64
            vfadd.vv.S
            ...
    rv64
        Vx8
        Vx16
        Vx32
        Vx64
        Vls8
        Vls16
        Vls32
        Vls64
        Vf16
        Vf32
        Vf64
    priv
        ExceptionsV.S
        ZicsrV.S
        SsstrictV.S

When an instruction's EEW is not a supported SEW, the coverage files and tests exclude the instruction from testing.  For example, vwadd.vv is not supported when SEW=32 and ELEN = 32 because it cannot widen to 64 bits.

The tests also account for unsupported register group overlap.  For example, a widening add vwadd.wv v0, v2, v2 is unspported because the source registers cannot be read with different EEWs.  On the other hand vwadd.vv v0, v1, v8 with LMUL=1 is supported even though the destination vd=v0 widens to write [v0-v1], which overlaps with vs2=v1.  The tests exercise all supported overlaps, but do not attempt any unsupported overlaps because the behavior is reserved and unpredictable.

==== Vector Configuration Parameters

The coverpoints and tests are parameterized by the minimum supported element width SEW~MIN~ and the maximum supported element width ELEN.  The coverpoints and tests exclude unsupported corner cases, such as widening to more than ELEN or using LMUL=1/8 with ELEN=32 but SEW~MIN~=8.

==== Vector Coverpoints

Running long vectors is computationally expensive, so only a subset of vectors tests run on mult-element vectors.  Coverpoints for source and destination registers, corner values, etc. run on a vector length of vl = 1.

Table *** defines the coverpoints used in vector instructions.  Unless otherwise specified, each coverpoint uses vector length vl=1 and length multiplier LMUL=1, no mask (vm=1), and vstart=0. Hence, they act on exactly one vector element. For such coverpoints, instructions that require a mask use v0=0.

[cols="2,1,5" options=header]
|===
|Coverpoint|# Bins|Definition
|cp_vd|32|All vector destination registers vd=0-31
|cp_vs2|32|All vector source registers vs2=0-31
|cp_vs1|32|All vector source registers vs1=0-31
|cp_vs3|32|All vector source registers vs3=0-31
|cp_rs1|32|All scalar registers rs1=0-31
|cp_rs2|32|All scalar registers rs2=0-31
|cp_imm_5bit|32|Signed immediate values -16 to +15
|cmp_rs1_rs2|32|rs1 and rs2 are same register ID
|cmp_vd_vs2|32|vd and vs2 are same register ID
|cmp_vd_vs1|32|vd and vs1 are same register ID
|cmp_vs2_vs1|32|vs2 and vs1 are same register ID
|cmp_vd_vs1_vs2|32|vd and vs1 and vs2 are same register ID
|cp_rs1_corners|9|0, 1, 2, -1, -2, most negative, most negative+1, most positive, most positive-1
|cp_fs1_corners|20|0, -1, -smallest subnorm, -inf, 1, 1+ulp, 0.5, 1.5, 2, 4, pi, 2^emax, largest normal, smallest normal, largest subnormal, subnormal with leading 1 in fraction, infinity, canonical quite NaN, noncanonical quiet NaN, signaling NaN with payload of 1
|cp_vs2_corners|9|see cp_rs1_corners
|cp_vs1_corners|9|see cp_rs1_corners
|cr_vs2_vs1_corners|9*9|Cross-product of corners of vs2 and vs1
|cr_vs2_rs1_corners|9*9|Cross-product of corners of vs2 and rs1
|cr_vs2_imm_corners|9*9|Cross-product of corners of vs2 and imm={0, 1, 2, 14, 15, -1, -2, -15,-16}
|cr_vxrm_vs2_vs1_corners|9*9*4|Cross-product of corners of vs2 and vs1 with vector rounding mode={rod, rdn, rne, rnu}
|cr_vxrm_vs2_rs1_corners|9*9*4|See cr_vxrm_vs2_vs1_corners
|cr_vxrm_vs2_imm_corners|9*9*4|See cr_vxrm_vs2_vs1_corners
|cp_frm_vs2_corners|5*20|Cross-product of corners of vs2 and floating-point rounding mode={rdn, rmm, rne, rtz, rup}
*** other fp corners
|cp_frm_vs1_vs2_corners|5*20*20|Cross-product of corners of vs1 and vs2 with frm
|cp_masking_corners|5|Mask corners v0=all 1s, all 0s, random, first VLMAX-1 ones, first VLMAX/2+1 ones; vl=VLMAX
|cr_vl_lmul|7*3|Cross legal combinations of LMUL={1/2/4/8/f2/f4/f8} and vl={1, random, VLMAX}, while randomizing whether to mask and the mask value
|cr_vtype_agnostic||Cross
|cp_vxsat|n/a|S
|cp_vl_0|1|vl=0
|cp_vtypei_legal|
|cp_rs2_vtype_legal_corners|
|cp_rs1_corners_avl|
|cp_rs2_corners_ls|
|cp_vs2_corners_ls|
|===

As with other unprivileged testplans, an x in the spreadsheet indicates to use the coverpoint.  Other values in the spreadsheet indicate a variant of the coverpoint:

* nv0: Do not include v0 in the coverpoint.  For example, cp_vd_nv0 means that the destination register vd does not include v0.
* emul2: Only exercise even-numbered registers.  For example cp_vs2_emul2 uses vs2={v0, v2, v4, ...v30}.  For corner values, emul2 means the corner value is twice the width of SEW.
* emul4/8: Similar to emul2
* emulf2, emulf4, emulf8: corner values are 1/2, 1/4, or 1/8 the width of SEW.  Used in extension instructions such as vsext.vf2.
* u: Treat immediate as unsigned 0 to 31 rather than signed -16 to +15. For corners, {0, 1, 2, 15, 16, 30, 31}.
* eew1/mm: Mask instructions with 1-bit elements such as vmand.mm use at least vl=8 to operate on multi-bit masks.
* wv: vs2 is double-width and uses emul2 for its corner values.  vs1 is normal width.
* wred: vs1 is double-width and uses emul2 for its corner values.  vs2 is normal width.
* wx: vs2 is double-width and uses emul2 for its corner values.  rs1 is normal width.
* wi/wiu: vs2 is double-width and uses emul2 for its corner values.  immediate is 5 bit signed or unsigned.
* lmul4max/emul4max: maximum LMUL/EMUL is 4 instead of 8.  vwadd.vv uses lmul4max because it cannot accept LMUL=8 widened to 16.  vlseg2e8.v uses emul4max because the number of segments * EMUL cannot exceed 8.
* lmul2max/lmul1max/emul2max/emul1max: see lmul4max
* lte30/.../lte24: Register number is less than or equal to 30, ..., 24.  Used for segmented load/store so segments won't overflow the register file.
* ls_e{8/16/32/64}: load/store corners with EEW=8,...,64.  Used to convert strided loads from elements to bytes.
* ls: load/store corners instead of integer corners: vs2={0, random < 2*VLMAX}.  rs2= {1, 2, -1, -2, 0}
* f: floating-point corners instead of integer corners: ***

*** discuss special cases

The coverpoints for each vector instruction are given in the following sections.

==== Vx

==== Vls

==== Vf

== Zvfh* Vector Half-Precision Floating-Point Extension

***

Note that half-precision vector floating-point is part of the Zvfh and Zvfhmin extensions, not the base V extension.  Nevertheless, all of these tests are in the same directory structure.



=== Zvb* Vector Bit Manipulation Extension

Vector bit manipulation extensions include Zvbb and Zvbc.

==== Zvbb Vector Basic Bit Manipulation Extension

==== Zvbc Vector Caryless Multiplication Extension

=== Zvk* Vector Cryptography Extension

There are several Zvk* vector cryptography extensions.  Zvks ShangMi extensions are not yet supported.

==== Zvkb Vector Crypto Bit Manipulation Extension

==== Zvkg Vector Crypto Galois Field Extension

==== Zvkned Vector NIST Encryption and Decryption

==== Zvknh{a/b} Vector NIST Hashing

== Privileged Test Plan

Privileged https://drive.google.com/drive/folders/11hTR2Yl48kOMODxhwrSsC-eXYtM_rJJE?usp=share_link:[test plan spreadsheets] are available.  They need to be edited into a more standarized format. Each test plan spreadsheet contains multiple columns for the applicable configurations.  For example, ZicsrM applies to any configuration with machine mode, ZicsrS applies to any configuration with supervisor mode, and ZicsrF applies to any configuration with floating-point.

* Zicsr
* Exceptions
* Interrupts
* PMP
* RV64CBO footnote:[why just 64?]
* Endian
* RVVM Virtual Memory
* Svinval
* Zicntr
* Ssstrict


ZicsrV
ExceptionsV
SsstrictV
