
== Privileged Test Plan

Privileged https://drive.google.com/drive/folders/11hTR2Yl48kOMODxhwrSsC-eXYtM_rJJE?usp=share_link:[test plan spreadsheets] are available.  They need to be edited into a more standarized format. Each test plan spreadsheet contains multiple columns for the applicable configurations.  For example, ZicsrM applies to any configuration with machine mode, ZicsrS applies to any configuration with supervisor mode, and ZicsrF applies to any configuration with floating-point.

[[t-I-priv-normative-statements]]
.I Privileged Normative Statements
[cols="1, 4, 2" options=header]
|===
|Unpriv Section|Normative Statement|Coverpoints
|2.2|The base ISA has IALIGN=32, meaning that instructions must
be aligned on a four-byte boundary in memory. An instruction-address-misaligned exception is
generated on a taken branch or unconditional jump if the target address is not IALIGN-bit aligned. This
exception is reported on the branch or jump instruction, not on the target instruction.|
|2.2|No instruction-address-misaligned exception is generated for a conditional branch that is not taken.|
|2.5|If an instruction access-fault or instruction page-fault exception
occurs on the target of a jump or taken branch, the exception is
reported on the target instruction, not on the jump or branch
instruction.|
|2.5.1|The JAL and JALR instructions will generate an
instruction-address-misaligned exception if the target address is not
aligned to a four-byte boundary.|
|2.5.2|The conditional branch instructions will generate an
instruction-address-misaligned exception if the target address is not
aligned to a four-byte boundary and the branch condition evaluates to
true.|
|2.5.2|If the branch condition evaluates to false, the
instruction-address-misaligned exception will not be raised.|
|2.5.2|Loads with a destination of
`x0` must still raise any exceptions and cause any other side effects
even though the load value is discarded.|
|2.5.2|The EEI will define whether the memory system is little-endian or
big-endian. In RISC-V, endianness is byte-address invariant.|
|2.6|Loads
and stores whose effective address is not naturally aligned to the
referenced datatype (i.e., the effective address is not divisible by the
size of the access in bytes) have behavior dependent on the EEI.| *** more in 2.6 spec
|2.8|The `ECALL` instruction is used to make a service request to the execution
environment.|
|2.8|The `EBREAK` instruction is used to return control to a debugging
environment.|
|===

=== Privileged Instructions

The privileged testplan is organized by major categories of behaviors or extensions.

* Zicsr
* Exceptions
* Interrupts
* Zicntr
* Endian
* Ssstrict
* Svinval
* PMP
* Virtual Memory
* *** CBO

Each of these categories has multiple coverage files with suffixes indicating the circumstances to which they apply.  For example, InterruptsM applies to any configuration with Zicsr and M-mode.  InterruptsU applies to any configuration with Zicsr and U-mode.  InterruptsS applies to any configuration with Zicsr and S-mode.  S-mode implies the presence of U and M modes so all three coverage files apply to a system with S-mode.  Moreover, InterruptsS includes tests that execute in U and M-mode, such as setting a bit in mideleg and then checking that the corresponding interrupt is delegated to S-mode when taken in U-mode, but not when taken in M-mode.

=== Zicsr

Zicsr privileged tests access to CSRs that are mandatory in each privilege mode.
It also tests mandatory privileged instructions: `ecall`, `ebreak`, `mret`, and `sret`.
The CSR read/write/set/clear instructions themselves are tested in the
unprivileged Zicsr tests of <<Zicsr Control/Status Register Instructions>>.

`wfi` is tested in <<Interrupts>> and `sfence.vma` is tested in <<Sv* Virtual Memory>>.

Zicsr does not test reserved or custom instructions or CSRs because their behavior is Unspecified.
Reserved instructions and CSRs are tested in the <<Ssstrict>> Ssstrict tests,
where they should throw an Illegal Instruction exception if not implemented.

==== ZicsrM

*** find all WPRI and WLRL fields.  Don't look at WPRI results.  Only test legal values of WLRL.
==== ZicsrS

==== ZicsrU

==== ZicsrF

==== ZicsrV

==== ZicsrUF

==== ZicsrUV


   TODO check WARL, WLRL, WPRI behaviors

=== Exceptions

==== ExceptionsM

==== ExceptionsS

==== ExceptionsU

==== ExceptionsF

==== ExceptionsV

==== ExceptionsZalrsc

==== ExceptionsZaammo

==== ExceptionsZc

==== ExceptionsZicboS

==== ExceptionsZicboU

==== ExceptionsVM

==== ExceptionsVMZalrsc

==== ExceptionsVMZaamo

=== Interrupts

==== InterruptsM

==== InterruptsS

==== InterruptsU

==== InterruptsSstc

=== Zicntr

counters and hpms

==== ZicntrM

==== ZicntrS

==== ZicntrU

=== Endian

==== EndianM

==== EndianS

==== EndianU

==== EndianZaamo

==== EndianZalrsc

=== Ssstrict

The Ssstrict extension indicates that reserved instructions throw an illegal instruction exception, delegated to supervisor mode.

==== SsstrictS

==== SsstrictV

*** get rid of SsstrictM


=== Svinval

=== PMP

==== PMPM

==== PMPS

==== PMPU

==== PMPZca

==== PMPZicbo

==== PMPZaamo

==== PMPZalrsc

=== Sv* Virtual Memory

==== RV32VM

==== RV32VM_PMP

==== RV64VM

==== RV64VM_PMP

=== CBO

*** why RV64CBO?

==== RV64CBO_VM

==== RV64CBO_PMP

include::hypervisor.adoc[]
