# yaml-language-server: $schema=../spec/schemas/config_schema.json
---
$schema: config_schema.json#
kind: architecture configuration
type: fully configured
name: cvw-rv32gc
description: The rv32gc configuration of Core-V Wally;
implemented_extensions:
  - { name: I, version: "2.1" }
  - { name: A, version: "2.1.0" }
  - { name: M, version: "2.0" }
  - { name: F, version: "2.2.0" }
  - { name: D, version: "2.2.0" }
  - { name: C, version: "2.0" }
  - { name: B, version: "1.0.0" }
  - { name: Zic64b, version: "1.0.0" }
  - { name: Zicbom, version: "1.0.0" }
  - { name: Zicbop, version: "1.0.0" }
  - { name: Zicboz, version: "1.0.0" }
  - { name: Ziccamoa, version: "1.0.0" }
  - { name: Ziccif, version: "1.0.0" }
  - { name: Ziccrse, version: "1.0.0" }
  - { name: Zicntr, version: "2.0" }
  - { name: Zicond, version: "1.0.0" }
  - { name: Zicsr, version: "2.0" }
  - { name: Zifencei, version: "2.0.0" }
  - { name: Zihpm, version: "2.0.0" }
  - { name: Za64rs, version: "1.0.0" }
  - { name: Zfa, version: "1.0.0" }
  - { name: Zfh, version: "1.0.0" }
  - { name: Zcb, version: "1.0.0" }
  - { name: Zbc, version: "1.0.0" }
  - { name: Zkn, version: "1.0.0" }
  - { name: Zkt, version: "1.0.0" }
  - { name: U, version: "1.0.0" }
  - { name: S, version: "1.12.0" }
  - { name: Ssccptr, version: "1.0.0" }
  - { name: Sscounterenw, version: "1.0.0" }
  - { name: Ssstrict, version: "1.0.0" }
  - { name: Sstc, version: "1.0.0" }
  - { name: Sstvala, version: "1.0.0" }
  - { name: Sstvecd, version: "1.0.0" }
  - { name: Ssu64xl, version: "1.0.0" }
  - { name: Sv39, version: "1.13.0" }
  - { name: Sv48, version: "1.13.0" }
  - { name: Svade, version: "1.0.0" }
  - { name: Svadu, version: "1.0.0" }
  - { name: Svbare, version: "1.0.0" }
  - { name: Svinval, version: "1.0.0" }
  - { name: Sm, version: "1.12.0" }
  - { name: Smpmp, version: "1.12.0" }
  - { name: Smhpm, version: "1.12.0" }

params:
  # A params
  MISALIGNED_AMO: false
  LRSC_RESERVATION_STRATEGY: reserve exactly enough to cover the access # XLEN size reservation
  LRSC_FAIL_ON_VA_SYNONYM: false
  LRSC_MISALIGNED_BEHAVIOR: always raise access fault
  LRSC_FAIL_ON_NON_EXACT_LRSC: false
  MUTABLE_MISA_A: false
  # M params
  MUTABLE_MISA_M: false
  # F params
  MUTABLE_MISA_F: false
  HW_MSTATUS_FS_DIRTY_UPDATE: precise
  MSTATUS_FS_LEGAL_VALUES: [0, 1, 2, 3]
  # D params
  MUTABLE_MISA_D: false
  # C params
  MUTABLE_MISA_C: false
  # B params
  MUTABLE_MISA_B: true
  # CBO params
  CACHE_BLOCK_SIZE: 64
  FORCE_UPGRADE_CBO_INVAL_TO_FLUSH: false
  # Zicntr params
  TIME_CSR_IMPLEMENTED: true
  # U params
  MUTABLE_MISA_U: false
  U_MODE_ENDIANNESS: dynamic
  UXLEN: 32
  TRAP_ON_ECALL_FROM_U: true
  # S params
  MUTABLE_MISA_S: false
  ASID_WIDTH: 16
  S_MODE_ENDIANNESS: dynamic
  SXLEN: 32
  REPORT_VA_IN_MTVAL_ON_LOAD_PAGE_FAULT: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_PAGE_FAULT: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_PAGE_FAULT: true
  REPORT_VA_IN_STVAL_ON_BREAKPOINT: true
  REPORT_VA_IN_STVAL_ON_LOAD_MISALIGNED: true
  REPORT_VA_IN_STVAL_ON_STORE_AMO_MISALIGNED: true
  REPORT_VA_IN_STVAL_ON_INSTRUCTION_MISALIGNED: true
  REPORT_VA_IN_STVAL_ON_LOAD_ACCESS_FAULT: true
  REPORT_VA_IN_STVAL_ON_STORE_AMO_ACCESS_FAULT: true
  REPORT_VA_IN_STVAL_ON_INSTRUCTION_ACCESS_FAULT: true
  REPORT_VA_IN_STVAL_ON_LOAD_PAGE_FAULT: true
  REPORT_VA_IN_STVAL_ON_STORE_AMO_PAGE_FAULT: true
  REPORT_VA_IN_STVAL_ON_INSTRUCTION_PAGE_FAULT: true
  REPORT_ENCODING_IN_STVAL_ON_ILLEGAL_INSTRUCTION: true
  STVAL_WIDTH: 64
  SCOUNTENABLE_EN:
    [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
  STVEC_MODE_DIRECT: true
  STVEC_MODE_VECTORED: true
  SATP_MODE_BARE: true
  TRAP_ON_ECALL_FROM_S: true
  TRAP_ON_SFENCE_VMA_WHEN_SATP_MODE_IS_READ_ONLY: true
  MSTATUS_FS_WRITABLE: true
  MSTATUS_VS_WRITABLE: false
  MSTATUS_VS_LEGAL_VALUES: [0]
  MSTATUS_TVM_IMPLEMENTED: true
  # Sm params
  MXLEN: 32
  PRECISE_SYNCHRONOUS_EXCEPTIONS: true
  TRAP_ON_ECALL_FROM_M: true
  TRAP_ON_EBREAK: true
  ARCH_ID: 0x24
  IMP_ID: 0x100
  VENDOR_ID_BANK: 0xC
  VENDOR_ID_OFFSET: 0x2
  MISALIGNED_LDST: true
  MISALIGNED_LDST_EXCEPTION_PRIORITY: low
  MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE: 4096 # check
  MISALIGNED_SPLIT_STRATEGY: custom # We fetch the lower and upper parts with two XLEN-sized fetchs and merge them
  TRAP_ON_ILLEGAL_WLRL: false
  TRAP_ON_UNIMPLEMENTED_INSTRUCTION: true
  TRAP_ON_RESERVED_INSTRUCTION: true
  TRAP_ON_UNIMPLEMENTED_CSR: true
  REPORT_VA_IN_MTVAL_ON_BREAKPOINT: true
  REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT: true
  REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION: true
  MTVAL_WIDTH: 64
  CONFIG_PTR_ADDRESS: 0
  PMA_GRANULARITY: 3 # Not explicit in config
  PHYS_ADDR_WIDTH: 56
  M_MODE_ENDIANNESS: dynamic
  MISA_CSR_IMPLEMENTED: true
  MTVEC_MODES: [0, 1]
  MTVEC_BASE_ALIGNMENT_DIRECT: 4
  MTVEC_BASE_ALIGNMENT_VECTORED: 4
  # Smpmp params
  NUM_PMP_ENTRIES: 16
  PMP_GRANULARITY: 4
  # Smhpm params
  HPM_COUNTER_EN:
    [
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
  HPM_EVENTS: [0]
  COUNTINHIBIT_EN:
    [
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
  MCOUNTENABLE_EN:
    [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
