##################################
# makefile_gen.py
#
# jcarlin@hmc.edu 6 Sept 2025
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Generate Makefile for tests
##################################

from pathlib import Path

from framework.config import Config
from framework.parse_test_constraints import TestMetadata

# Makefile templates
MAKEFILE_HEADER = """
# This Makefile is auto-generated by cvw-arch-verif. Do not edit directly.
.DEFAULT_GOAL := compile
.PHONY: compile
"""


def gen_compile_targets(
    test_name: str,
    test_metadata: TestMetadata,
    base_dir: Path,
    xlen: int,
    mabi: str,
    config: Config,
) -> str:
    # Define paths
    build_dir = base_dir / "build"
    elf_dir = base_dir / "elfs"
    base_name = test_name.replace(".S", "")
    sig_elf = build_dir / f"{base_name}-sig.elf"
    sig_file = build_dir / f"{base_name}.sig"
    sig_log_file = build_dir / f"{base_name}-sig.log"
    final_elf = elf_dir / f"{base_name}.elf"

    # Extract metadata
    march = test_metadata.march
    flen = test_metadata.flen
    test_path = test_metadata.test_path
    ref_model_sig_flags = config.ref_model_type.signature_flags.format(sig_file=sig_file, granularity=int(xlen / 8))

    return f"""
# Generate signature based ELF
{sig_elf}: {test_path} | {sig_elf.parent}
\t{config.compiler_string} $(CFLAGS) \\
\t-o {sig_elf} \\
\t-march={march} -mabi={mabi} -DSIGNATURE -DXLEN={xlen} -DFLEN={flen} \\
\t{test_path}

# Generate signature file
{sig_file}: {sig_elf}
\t{config.ref_model_exe} --config {config.dut_include_dir}/sail.json {ref_model_sig_flags} \\
\t{sig_elf} > {sig_log_file}  # TODO: don't hardcode sail config file

# Final ELF target
{final_elf}: {sig_elf} {sig_file} | {final_elf.parent}
\t{config.compiler_string} $(CFLAGS) \\
\t-o {final_elf} \\
\t-march={march} -mabi={mabi} -DSELFCHECK -DXLEN={xlen} -DFLEN={flen} -DSIGNATURE_FILE='{sig_file}' \\
\t{test_path}
\t# Objdump
{
        f"\t{config.objdump_exe} -S -M no-aliases {final_elf} > {final_elf}.objdump"
        if config.objdump_exe is not None
        else "# skipping objdump generation"
    }
"""


def gen_rvvi_targets(test_name: str, base_dir: Path, config: Config) -> str:
    base_name = test_name.replace(".S", "")
    elf = base_dir / "elfs" / f"{base_name}.elf"
    sail_log = base_dir / "build" / f"{base_name}.log"
    rvvi_trace = base_dir / "build" / f"{base_name}.rvvi"

    return f"""
# Run test on Sail to generate log
{sail_log}: {elf}
\t{config.ref_model_exe} --trace-all {elf} --trace-output {sail_log}

# Generate RVVI trace
{rvvi_trace}: {sail_log}
\tuv run tools/sail-parse.py {sail_log} {rvvi_trace}
"""


def generate_common_makefile(
    config: Config,
    common_test_list: dict[str, TestMetadata],
    tests_dir: Path,
    wkdir: Path,
    xlen: int,
    mabi: str,
) -> None:
    """Generate a Makefile to compile the common tests."""
    common_wkdir = wkdir / "common"
    common_elf_dir = common_wkdir / "elfs"
    common_build_dir = common_wkdir / "build"
    makefile_lines = [
        MAKEFILE_HEADER,
        f"CFLAGS += -O0 -g -mcmodel=medany -nostartfiles -I{tests_dir}/env -I{tests_dir}/priv/headers",
        f"XLEN := {xlen}",
        "",
    ]
    directory_set = {str(common_elf_dir), str(common_build_dir)}  # Directories to create
    test_targets = []

    for test_name, test_metadata in common_test_list.items():
        elf_name = test_name.replace(".S", ".elf")
        final_elf = common_elf_dir / elf_name
        test_targets.append(f"\t{final_elf} \\")
        directory_set.update([str((common_elf_dir / test_name).parent), str((common_build_dir / test_name).parent)])
        makefile_lines.append(gen_compile_targets(test_name, test_metadata, common_wkdir, xlen, mabi, config))

    # Add TESTS variable and targets
    makefile_lines.append("TESTS = \\")
    makefile_lines.extend(test_targets)
    makefile_lines.append("\ncompile: $(TESTS)\n")

    # Directory creation rules
    makefile_lines.extend([f"{' '.join(directory_set)}:", "\tmkdir -p $@", ""])

    # Write out Makefile
    makefile_path = common_wkdir / f"rv{xlen}" / "Makefile"
    makefile_path.parent.mkdir(parents=True, exist_ok=True)
    makefile_path.write_text("\n".join(makefile_lines))


def generate_config_makefile(
    config: Config,
    config_test_list: dict[str, TestMetadata],
    common_test_list: dict[str, TestMetadata],
    tests_dir: Path,
    wkdir: Path,
    config_name: str,
    xlen: int,
    mabi: str,
) -> None:
    """Generate a Makefile to compile the config-specific tests."""
    config_wkdir = wkdir / config_name
    config_elf_dir = config_wkdir / "elfs"
    config_build_dir = config_wkdir / "build"
    common_wkdir = wkdir / "common"
    common_elf_dir = common_wkdir / "elfs"
    makefile_lines = [
        f"CFLAGS += -O0 -g -mcmodel=medany -nostartfiles -I{tests_dir}/env -I{tests_dir}/priv/headers",
        f"XLEN := {xlen}",
    ]
    directory_set = {str(config_elf_dir), str(config_build_dir)}  # Directories to create
    test_targets = []

    for test_name, test_metadata in config_test_list.items():
        elf_name = test_name.replace(".S", ".elf")
        final_elf = config_elf_dir / elf_name
        test_targets.append(f"\t{final_elf} \\")
        directory_set.update([str((config_elf_dir / test_name).parent), str((config_build_dir / test_name).parent)])
        if test_name in common_test_list:
            common_elf = common_elf_dir / elf_name
            makefile_lines.extend(
                [
                    f"{final_elf}: {common_elf} | {final_elf.parent}",
                    f"\tln -sf {common_elf} {final_elf}",
                    f"\tln -sf {common_elf}.objdump {final_elf}.objdump"
                    if config.objdump_exe is not None
                    else "# skipping objdump",
                    "",
                ]
            )
        else:
            makefile_lines.append(gen_compile_targets(test_name, test_metadata, config_wkdir, xlen, mabi, config))

    # Add TESTS variable and compile target
    makefile_lines.append("TESTS = \\")
    makefile_lines.extend(test_targets)
    makefile_lines.append("\ncompile: $(TESTS)\n")

    # Directory creation rules
    makefile_lines.extend([f"{' '.join(directory_set)}:", "\tmkdir -p $@", ""])

    # Write out Makefile
    config_wkdir.mkdir(parents=True, exist_ok=True)
    makefile_path = config_wkdir / "Makefile"
    makefile_path.write_text("\n".join(makefile_lines))


def generate_makefiles(
    configs: list[dict],
    rv32_common_tests: dict[str, TestMetadata],
    rv64_common_tests: dict[str, TestMetadata],
    tests_dir: Path,
    workdir: Path,
) -> None:
    """Generate Makefiles for multiple configurations with shared common directories."""
    rv32_common_generated = False
    rv64_common_generated = False
    top_makefile_lines = [MAKEFILE_HEADER]
    config_targets = []

    for config_data in configs:
        # Unpack config data
        config = config_data["config"]
        udb_config = config_data["udb_config"]
        selected_tests = config_data["selected_tests"]

        # Extract config parameters
        config_name = udb_config["name"]
        xlen = udb_config["params"]["MXLEN"]
        mabi = f"{'i' if xlen == 32 else ''}lp{xlen}"
        common_tests = rv32_common_tests if xlen == 32 else rv64_common_tests

        # Update top-level Makefile
        config_targets.append(f"{config_name}-compile")
        top_makefile_lines.extend(
            [
                f"{config_name}-compile: common-rv{xlen}-compile",
                f"\t$(MAKE) -C {config_name} compile",
                "",
            ]
        )

        # Generate config-specific Makefile
        generate_config_makefile(
            config,
            selected_tests,
            common_tests,
            tests_dir,
            workdir,
            config_name,
            xlen,
            mabi,
        )

        # Generate architecture-specific common Makefiles using first config of each XLEN
        if (xlen == 32 and not rv32_common_generated) or (xlen == 64 and not rv64_common_generated):
            generate_common_makefile(config, common_tests, tests_dir, workdir, xlen, mabi)
            top_makefile_lines.extend(
                [
                    f"common-rv{xlen}-compile:",
                    f"\t$(MAKE) -C common/rv{xlen} compile",
                    "",
                ]
            )

    # Write top-level Makefile
    top_makefile_lines.append(f"compile: {' '.join(config_targets)}")
    top_makefile = workdir / "Makefile"
    top_makefile.write_text("\n".join(top_makefile_lines))
