# yaml-language-server: $schema=../spec/schemas/config_schema.json
---
$schema: config_schema.json#
kind: architecture configuration
type: fully configured
name: cvw-rv32imc
description: The rv32imc configuration of Core-V Wally;
implemented_extensions:
  - { name: I, version: "2.1" }
  - { name: M, version: "2.0" }
  - { name: C, version: "2.0" }
  - { name: Zicntr, version: "2.0" }
  - { name: Zicsr, version: "2.0" }
  - { name: Zihpm, version: "2.0.0" }
  - { name: U, version: "1.0.0" }
  - { name: Sm, version: "1.12.0" }
  - { name: Smhpm, version: "1.12.0" }

params:
  # M params
  MUTABLE_MISA_M: false
  # C params
  MUTABLE_MISA_C: false
  # Zicntr params
  TIME_CSR_IMPLEMENTED: true
  # U params
  MUTABLE_MISA_U: false
  U_MODE_ENDIANNESS: little
  UXLEN: 32
  TRAP_ON_ECALL_FROM_U: true
  # Sm params
  MXLEN: 32
  PRECISE_SYNCHRONOUS_EXCEPTIONS: true
  TRAP_ON_ECALL_FROM_M: true
  TRAP_ON_EBREAK: true
  ARCH_ID: 0x24
  IMP_ID: 0x100
  VENDOR_ID_BANK: 0xC
  VENDOR_ID_OFFSET: 0x2
  MISALIGNED_LDST: true
  MISALIGNED_LDST_EXCEPTION_PRIORITY: low
  MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE: 4096 # check
  MISALIGNED_SPLIT_STRATEGY: custom # We fetch the lower and upper parts with two XLEN-sized fetchs and merge them
  TRAP_ON_ILLEGAL_WLRL: false
  TRAP_ON_UNIMPLEMENTED_INSTRUCTION: true
  TRAP_ON_RESERVED_INSTRUCTION: true
  TRAP_ON_UNIMPLEMENTED_CSR: true
  REPORT_VA_IN_MTVAL_ON_BREAKPOINT: true
  REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED: true
  REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT: true
  REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT: true
  REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION: true
  MTVAL_WIDTH: 64
  CONFIG_PTR_ADDRESS: 0
  PMA_GRANULARITY: 3 # Not explicit in config
  PHYS_ADDR_WIDTH: 56
  M_MODE_ENDIANNESS: little
  MISA_CSR_IMPLEMENTED: true
  MTVEC_MODES: [0, 1]
  MTVEC_BASE_ALIGNMENT_DIRECT: 4
  MTVEC_BASE_ALIGNMENT_VECTORED: 4
  # Smhpm params
  HPM_COUNTER_EN:
    [
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
  HPM_EVENTS: [0]
  COUNTINHIBIT_EN:
    [
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
  MCOUNTENABLE_EN:
    [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ]
