
=== A Atomic Extension

The A extension is subdivided into Zaamo and Zalrsc.
 <<t-A-normative-statements>> lists the normative statements in the RV{32/64}A specification applicable to all instructions, and the unprivileged coverpoints that exercise them.

[[t-A-normative-statements]]
.A Normative Statements
[cols="1, 4, 2" options=header]
|===
|Unpriv Section|Normative Statement|Coverpoints
|===

<<t-A-priv-normative-statements>> summarizes normative statements relating to atomic instructions affecting privileged behavior.

==== Zaamo Atomic Memory Operations Extension

<<t-Zaamo-coverpoints>> summarizes the coverpoints for the Zaamo extension.

[[t-Zaamo-coverpoints]]
.Zaamo Instruction Coverpoints
include::{testplansdir}/Zaamo.adoc[]

[[t-Zaamo-normative-statements]]
.Zaamo Normative Statements
[cols="1, 4, 2" options=header]
|===

|===

==== Zalrsc Load-Reserved / Store-Conditional Extension

<<t-Zalrsc-coverpoints>> summarizes the coverpoints for the Zalrsc extension.

[[t-Zalrsc-coverpoints]]
.Zalrsc Instruction Coverpoints
include::{testplansdir}/Zalrsc.adoc[]

[[t-Zalrsc-normative-statements]]
.Zalrsc Normative Statements
[cols="1, 4, 2" options=header]
|===
|===

***
On implementations that support the C extension, compressed forms of the
I instructions permitted inside constrained LR/SC sequences, as
described in <<sec:lrscseq>>, are also perm
