
=== Exceptions

Exception tests are organized according to the privilege mode or extension supported.  For example, a configuration with Machine, Supervisor, User, and Floating-Point supported should run ExceptionsM, ExceptionsS, ExceptionsU, and ExceptionsF.

==== ExceptionsM Machine-Mode Exceptions

These tests are run on any configuration with machine mode that supports exceptions.

[[t-ExceptionsM-coverpoints]]
.ExceptionsM Coverpoints
,===
//include::{testplansdir}/ExceptionsM.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1987812700#gid=1987812700[Google Sheet Testplan]

==== ExceptionsS Supervisor-Mode Exceptions

These additional exception tests are run on configurations with supervisor mode.

[[t-ExceptionsS-coverpoints]]
.ExceptionsS Coverpoints
,===
//include::{testplansdir}/ExceptionsS.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=2127390256#gid=2127390256[Google Sheet Testplan]

==== ExceptionsU User-Mode Exceptions

These additional exception tests are run on configurations with user mode.

[[t-ExceptionsU-coverpoints]]
.ExceptionsU Coverpoints
,===
//include::{testplansdir}/ExceptionsU.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=593261374#gid=593261374[Google Sheet Testplan]

==== ExceptionsF Floating-Point Exceptions

These additional exception tests are run on configurations with floating-point (at least the F extension).

[[t-ExceptionsF-coverpoints]]
.ExceptionsF Coverpoints
,===
//include::{testplansdir}/ExceptionsF.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1241522932#gid=1241522932[Google Sheet Testplan]

==== ExceptionsV Vector Exceptions

These additional exception tests are run on configurations with vector (V extension or subsets thereof that rely on mstatus.VS).

[[t-ExceptionsV-coverpoints]]
.ExceptionsV Coverpoints
,===
//include::{testplansdir}/ExceptionsV.adoc[]
,===

*** add link

==== ExceptionsZalrsc Atomic LR/SC Exceptions

[[t-ExceptionsZalrsc-coverpoints]]
.ExceptionsZalrsc Coverpoints
,===
//include::{testplansdir}/ExceptionsZalrsc.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=891200072#gid=891200072[Google Sheet Testplan]

==== ExceptionsZaamo Atomic Memory Operation Exceptions

[[t-ExceptionsZaamo-coverpoints]]
.ExceptionsZaamo Coverpoints
,===
//include::{testplansdir}/ExceptionsZaamo.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=2143559149#gid=2143559149[Google Sheet Testplan]

==== ExceptionsZc Compressed Instruction Exceptions

These additional exception tests are run on configurations with compressed instructions (C, Zca, Zcb, etc.).  They attempt to test all compressed loads and stores, but may throw an illegal instruction fault on compressed subword load/store if Zcb is not supported.

[[t-ExceptionsZc-coverpoints]]
.ExceptionsZc Coverpoints
,===
//include::{testplansdir}/ExceptionsZc.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=538759067#gid=538759067[Google Sheet Testplan]

==== ExceptionsZicboS Supervisor-Mode CBO Exceptions

[[t-ExceptionsZicboS-coverpoints]]
.ExceptionsZicboS Coverpoints
,===
//include::{testplansdir}/ExceptionsZicboS.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=927893239#gid=927893239[Google Sheet Testplan]

==== ExceptionsZicboU User-Mode CBO Exceptions

[[t-ExceptionsZicboU-coverpoints]]
.ExceptionsZicboU Coverpoints
,===
//include::{testplansdir}/ExceptionsZicboU.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1054505393#gid=1054505393[Google Sheet Testplan]

==== ExceptionsVM Virtual Memory Exceptions

[[t-ExceptionsVM-coverpoints]]
.ExceptionsVM Coverpoints
,===
//include::{testplansdir}/ExceptionsVM.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=270777025#gid=270777025[Google Sheet Testplan]

==== ExceptionsVMZalrsc  Virtual Memory LR/SC Exceptions

[[t-ExceptionsVMZalrsc-coverpoints]]
.ExceptionsVMZalrsc Coverpoints
,===
//include::{testplansdir}/ExceptionsVMZalrsc.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=287426144#gid=287426144[Google Sheet Testplan]

==== ExceptionsVMZaamo Virtual Memory AMO Exceptions

[[t-ExceptionsVMZaamo-coverpoints]]
.ExceptionsM Coverpoints
,===
//include::{testplansdir}/ExceptionsVMZaamo.adoc[]
,===
https://docs.google.com/spreadsheets/d/1W95I4jPbuQBnXzDdIZtOG4kae8vi7djpKtJXWCXPxMU/edit?gid=1747092954#gid=1747092954[Google Sheet Testplan]

==== Zicclsm Misaligned Loads/Stores

Misaligned loads/stores handled in hardware.

[[t-Zicclsm-coverpoints]]
.Zicclsm Coverpoints
,===
//include::{testplansdir}/Zicclsm.adoc[]
,===
*** need to create this
