
=== PMP

==== PMPM

[[t-PMPM-coverpoints]]
.PMPM Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPM.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=1474055416#gid=1474055416[Google Sheet Testplan]

==== PMPS

[[t-PMPS-coverpoints]]
.PMPS Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPS.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=1908943019#gid=1908943019[Google Sheet Testplan]

==== PMPU

[[t-PMPU-coverpoints]]
.PMPU Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPU.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=2072825600#gid=2072825600[Google Sheet Testplan]

==== PMPF

[[t-PMPF-coverpoints]]
.PMPF Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPF.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=1472001893#gid=1472001893[Google Sheet Testplan]

==== PMPZca

[[t-PMPZca-coverpoints]]
.PMPZca Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPZca.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=1336315481#gid=1336315481[Google Sheet Testplan]

==== PMPZicbo

[[t-PMPZicbo-coverpoints]]
.PMPZicbo Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPZicbo.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=1958410505#gid=1958410505[Google Sheet Testplan]

==== PMPZaamo

[[t-PMPZaamo-coverpoints]]
.PMPZaamo Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPZaamo.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=343093009#gid=343093009[Google Sheet Testplan]

==== PMPZalrsc

[[t-PMPZalrsc-coverpoints]]
.PMPZalrsc Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/PMPZalrsc.adoc[]
,===
https://docs.google.com/spreadsheets/d/1jvJCSf9vdZ23PEaaYETLxfwZoyq_PzpyJzIB1OhdhcQ/edit?gid=613653829#gid=613653829[Google Sheet Testplan]

==== RV32CBO_PMP

*** try to get rid of RV64 part

[[t-RV32CBO_PMP-coverpoints]]
.RV32CBO_PMP Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/RV32CBO_PMP.adoc[]
,===

*** are these needed?  Seems like they should have VM in the name as well
because they depend on the PTE.  Maybe these should move to the VM section?

==== RV64CBO_PMP

*** try to get rid of RV64 part

[[t-RV64CBO_PMP-coverpoints]]
.RV64CBO_PMP Coverpoints
[options=header]
[%AUTOWIDTH]
,===
//include::{testplansdir}/RV64CBO_PMP.adoc[]
,===

*** are these needed?  Seems like they should have VM in the name as well
because they depend on the PTE.  Maybe thse should move to the VM section?
