
=== Zicsr

Zicsr privileged tests access to CSRs that are mandatory in each privilege mode.
It also tests mandatory privileged instructions: `ecall`, `ebreak`, `mret`, and `sret`.
The CSR read/write/set/clear instructions themselves are tested in the
unprivileged Zicsr tests of <<Zicsr Control/Status Register Instructions>>.

`wfi` is tested in <<Interrupts>> and `sfence.vma` is tested in <<Sv* Virtual Memory>>.

Zicsr does not test reserved or custom instructions or CSRs because their behavior is Unspecified.
Reserved instructions and CSRs are tested in the <<Ssstrict>> Ssstrict tests,
where they should throw an Illegal Instruction exception if not implemented.

==== ZicsrM

These test CSRs that exist in machine mode.

[[t-ZicsrM-coverpoints]]
.ZicsrM Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrM.csv[]
,===

*** find all WPRI and WLRL fields.  Don't look at WPRI results.  Only test legal values of WLRL.
  TODO check WARL, WLRL, WPRI behaviors


==== ZicsrS

These test additional CSRs that exist in supervisor mode.

[[t-ZicsrS-coverpoints]]
.ZicsrS Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrS.csv[]
,===

==== ZicsrU

These test additional CSRs that exist in user mode.

[[t-ZicsrU-coverpoints]]
.ZicsrU Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrU.csv[]
,===

==== ZicsrF

These test additional CSRs that exist when floating-point is supported.

[[t-ZicsrF-coverpoints]]
.ZicsrF Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrF.csv[]
,===

==== ZicsrV

These test additional CSRs that exist when vector is supported.

[[t-ZicsrV-coverpoints]]
.ZicsrV Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrV.csv[]
,===

==== ZicsrUF

These test additional CSR scenarios that exist when floating-point and user mode are supported.

[[t-ZicsrUF-coverpoints]]
.ZicsrUF Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrUF.csv[]
,===

==== ZicsrUV

These test additional CSR scenarios that exist when vector and user mode are supported.

[[t-ZicsrUV-coverpoints]]
.ZicsrUV Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrUV.csv[]
,===


==== ZicsrZkr

These test CSRs when the Zkr entropy extension is supported.

[[t-ZicsrZkr-coverpoints]]
.ZicsrZkr Coverpoints
[options=header]
[%AUTOWIDTH]
,===
include::{testplansdir}/ZicsrZkr.csv[]
,===
