compiler_exe: /opt/riscv/bin/riscv64-unknown-elf-gcc # executable name on $PATH or full path to executable
objdump_exe: /opt/riscv/bin/riscv64-unknown-elf-objdump # executable name on $PATH or full path to executable, optional
ref_model_exe: /opt/riscv/bin/sail_riscv_sim # executable name on $PATH or full path to executable
ref_model_type: sail # sail or spike
udb_config: cvw-rv64gc.yaml
linker_script: link.ld
dut_include_dir: . # Directory containing DUT specific model_test.h header
